apiVersion: v1
kind: Pod
metadata:
  nome: web-server-pod
  labels:
    type: web-server-app

spec:
  containers:
  - name: web-server-apache
    image: httpd
    ports:
    - containerPort: 80
  - name: web-server-tomcat
    image: tomcat
    ports:
    - containerPort: 8080